name: deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Reconfigure git to use HTTP authentication # https://github.com/actions/setup-node/issues/214#issuecomment-810829250
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/

      - name: Run Linter
        uses: stefanoeb/eslint-action@1.0.2

      - name: Deploy App to Remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE}}
          script: sh deploy.sh